# .streamlit/config.toml - 수정된 버전 (중복 제거)

[global]
# 개발 모드 설정 (배포시 자동으로 False)
developmentMode = false

# 사용량 통계 수집 (선택사항)
gatherUsageStats = false

# 로그 레벨 설정
logLevel = "info"

# DataFrame 직렬화 방식 (중복 제거됨)
[global.dataFrameSerialization]
engine = "arrow"

[server]
# 포트 설정 (Streamlit Cloud에서는 자동 설정)
port = 8501

# 헤드리스 모드 (서버 환경용)
headless = true

# 파일 업로드 크기 제한 (MB)
maxUploadSize = 200

# 메시지 크기 제한 (MB)
maxMessageSize = 200

# CORS 설정 (모든 도메인 허용)
enableCORS = false

# XSS 보호 활성화
enableXsrfProtection = true

[browser]
# 자동으로 브라우저 열기 (로컬 개발시에만)
gatherUsageStats = false

# 서버 주소 (Streamlit Cloud에서는 자동 설정)
serverAddress = "localhost"

[theme]
# 기본 테마 설정 (light/dark)
base = "light"

# 기본 색상 (선택사항 - 주석 해제하여 커스터마이징)
# primaryColor = "#667eea"
# backgroundColor = "#ffffff"
# secondaryBackgroundColor = "#f0f2f6"
# textColor = "#262730"

[client]
# 툴바 모드 (minimal/developer/viewer)
toolbarMode = "minimal"

# 사이드바 초기 상태 (auto/expanded/collapsed)
showSidebarNavigation = true

[runner]
# 매직 명령어 활성화
magicEnabled = true

# 파일 변경시 자동 재실행 (개발 모드)
fastReruns = true

# 실행 결과 캐싱
enforceSerializableSessionState = false

[logger]
# 로그 레벨
level = "info"

# 메시지 형식
messageFormat = "%(asctime)s.%(msecs)03d %(name)s: %(levelname)s: %(message)s"

[deprecation]
# 경고 메시지 표시
showPyplotGlobalUse = false